[project]
name = "slack-events-bot"
description = "An automated Slack bot to syndicate local events into Slack channels in a weekly digest format. Event data is sourced from HackGreenville Labs Events API."
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
version="0.1.0"
authors = [
  { name = "Olivia Sculley", email = "olivia@sculley.dev" },
]
keywords = [
  "automation",
  "black",
  "bolt",
  "bot",
  "pylint",
  "pytest",
  "slack"
]
dependencies = [
  "aiohttp==3.8.5",
  "aiosignal==1.3.1",
  "annotated-types==0.5.0",
  "anyio==3.7.1",
  "async-timeout==4.0.3",
  "attrs==23.1.0",
  "certifi==2023.7.22",
  "charset-normalizer==3.2.0",
  "click==8.1.7",
  "fastapi==0.103.2",
  "frozenlist==1.4.0",
  "h11==0.14.0",
  "httpcore==0.18.0",
  "httpx==0.25.0",
  "idna==3.4",
  "iniconfig==2.0.0",
  "multidict==6.0.4",
  "packaging==23.1",
  "pluggy==1.3.0",
  "pydantic==2.4.2",
  "pydantic_core==2.10.1",
  "pytest==7.4.2",
  "python-dateutil==2.8.2",
  "pytz==2023.3",
  "six==1.16.0",
  "slack-bolt==1.18.0",
  "slack-sdk==3.22.0",
  "sniffio==1.3.0",
  "starlette==0.27.0",
  "typing_extensions==4.8.0",
  "uvicorn==0.23.2",
  "yarl==1.9.2"
]

[project.urls]
Homepage = "https://github.com/hackgvl/slack-events-bot"
Documentation = "https://github.com/hackgvl/slack-events-bot/blob/dev/README.md"
Repository = "https://github.com/hackgvl/slack-events-bot.git"

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "src"
]
