name: Run CI

on: [push]

jobs:
  lint_and_test:
    strategy:
      matrix:
        python_version: ['3.11.5']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Black
        uses: microsoft/action-python@0.7.0
        with:
          black: true
          python_version: ${{ matrix.python_version }}

      - name: Pylint
        uses: microsoft/action-python@0.7.0
        with:
          pylint: true
          python_version: ${{ matrix.python_version }}

      - name: Pytest
        uses: microsoft/action-python@0.7.0
        with:
          pytest: true
          workdir: '.'
          python_version: ${{ matrix.python_version }}

